name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: ./.github/actions
      env:
        DOCKER_USERNAME: ${{ github.event_name != 'pull_request' && secrets.DOCKER_USERNAME || '' }}
        DOCKER_PASSWORD: ${{ github.event_name != 'pull_request' && secrets.DOCKER_PASSWORD || '' }}
      with:
        version: 1.12.0
        tags: 1.12,1,latest
        platform: linux/amd64
